version: "3"
services: 
 react-app: 
   build: 
     context: ./dsu-si-week-3-front 
   image: jumpstonik/dsu-si-front 
   ports: 
     - "3000:3000"
   stdin_open: true
 api-server:
   build:
     context: ./dsu-si-backend
   image: jumpstonik/dsu-si-back
   ports:
     - "3001:3001"
   depends_on:
     - mongoInstance
 mongoInstance:
    image: mongo
    restart: always
    ports:
      - 27017:27017