version: "3.9" 
services:
  db:
    image: mongo
    container_name: dbmongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - dsu-si-net

  backend:
    image: racarlosdavid/dsu_backend_chatapp
    container_name: backend
    environment:
      MONGO_HOST: dbmongo
      TOKEN_SECRET: Rocinante92129Alpha
    ports:
    - 3001:3001
    restart: always
    depends_on:
    - db
    networks:
    - dsu-si-net

  frontend:
    image: racarlosdavid/dsu_frontend_chatapp
    container_name: frontend
    environment:
      REACT_APP_BACKEND_URL: http://192.168.1.13:3001
    ports:
    - 3000:3000
    restart: always
    depends_on:
    - backend
    networks:
    - dsu-si-net
  
volumes:
  mongodata:

networks:
  dsu-si-net:
    name: "dsu-si-net"
    driver: bridge